---
ansible_user: ansible
ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36356230663365626165396563623334333164313162306430373862333838636638333735393632
          6633626333363163623035343538363632373261636663610a663335633333346238333264383465
          33643334383266333235333366386539383737643136323736636333633834663037363666303962
          3138323239636561340a346439623364626662303833366532336533613864316266643564656430
          32393764653437323534646336666235373162643731303862353564386534326234
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
