---
- hosts: linux
  gather_facts: false

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: install nginx
      package:
        name:
          - nginx
        state: latest
      become: true

    - name: copy index.html
      copy:
        src: index.html
        dest: /usr/share/nginx/html/index.html
        mode: 0644
      become: true

    - name: start nginx service
      service:
        name: nginx
        state: started
      become: true
