---
    - hosts: all
      gather_facts: false

      vars_prompt:
        - name: user
          prompt: "Enter ssh user"
          private: no
        - name: password
          prompt: "Enter password for ssh user"
    
      vars:
        ansible_user: "{{ user }}"
        ansible_password: "{{ password }}"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        
      tasks:
      - name: install nginx
        package:
          name:
            - nginx
          state: latest
        become: yes

      - name: copy index.html
        copy:
          src: index.html
          dest: /usr/share/nginx/html/index.html
        become: yes
      
      - name: start nginx service
        service:
            name: nginx
            state: started
        become: yes
